language: python
python:
  - "3.8"

before_install:
  - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)/src"
  
install:
  - pip install cx-freeze
  - pip install ply
  - pip install pytest-cov
  - pip install pyqt5
  - pip install pytest-qt
  - pip install -e .

# command to run tests
script:
  - pytest --cov=src tests/

after_success:
  - bash <(curl -s https://codecov.io/bash) -v
