language: python
python:
  - "3.8"

addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
services: xvfb
dist: xenial  
install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)/src"
  - pip install cx-freeze
  - pip install ply
  - pip install pytest-cov
  - pip install pyqt5
  - pip install pytest-qt
  - pip install -e .

# command to run tests
script:
  - pytest --cov=src tests/

after_success:
  - bash <(curl -s https://codecov.io/bash) -v
