language: python
python:
  - "3.8"
addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
services: xvfb
install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb herbstluftwm
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)/src"
  - pip install cx-freeze
  - pip install ply
  - pip install pytest-cov
  - pip install pyqt5
  - pip install pytest-qt
  - pip install -e .
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  - sleep 3

before_script:
  - "herbstluftwm &"
  - sleep 2

script:
  - QT_DEBUG_PLUGINS=1 python -m pytest --cov=src tests/

after_success:
  - bash <(curl -s https://codecov.io/bash) -v
