language: python
python:
  - "3.8"

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)/src"
  
install:
  - pip install cx-freeze
  - pip install pytest-cov
  - pip install pytest-pylint
  - pip install -e .

# command to run tests
script:
  - pytest --pylint --cov=src tests/

after_success:
  - bash <(curl -s https://codecov.io/bash) -v
